--BOOK 테이블 데이터를 화면 출력 
DECLARE
    V_BOOKID NUMBER(2);
    V_BOOKNAME VARCHAR(40);
    V_PUBLISHER VARCHAR(40);
    V_PRICE NUMBER(8);
BEGIN
    --SELECT ~ INTO ~ FROM 형태로 DB 데이터 선택하고 INTO절 변수에 저장 
    --1개의 데이터만 처리 가능
   SELECT BOOKID, BOOKNAME, PUBLISHER, PRICE
   INTO V_BOOKID, V_BOOKNAME, V_PUBLISHER, V_PRICE
   FROM BOOK 
   WHERE BOOKID = 4;
   
   DBMS_OUTPUT.PUT_LINE(V_BOOKID ||','||V_BOOKNAME||','||V_PUBLISHER||','||V_PRICE);
   
END;