SELECT BOOKID, BOOKNAME, GET_BOOKNAME(BOOKID)
FROM BOOK;

SELECT O.*, GET_BOOKNAME(BOOKID) 
FROM ORDERS O;

-- GET_CUSTNAME 함수 사용해서 고객명 검색 여부 확인해보기
SELECT GET_CUSTNAME(CUSTID) FROM CUSTOMER;
SELECT GET_CUSTNAME(1) FROM DUAL;
SELECT GET_CUSTNAME(3) FROM DUAL;
-- ORDERS 테이블 데이터 조회
SELECT O.*, GET_CUSTNAME(CUSTID) AS NAME FROM ORDERS O;
---- GET_BOOKNAME, GET_CUSTNAME 함수사용 주문(판매)정보와 책제목, 고객명 조회
SELECT GET_CUSTNAME(CUSTID) AS NAME, GET_BOOKNAME(BOOKID) AS BOOKNAME, O.* FROM ORDERS O;

SELECT GET_CUSTNAME(CUSTID) AS NAME, GET_BOOKNAME(BOOKID) AS BOOKNAME, O.* FROM ORDERS O 
WHERE GET_BOOKNAME(BOOKID) LIKE '%축구%';

SELECT GET_CUSTNAME(CUSTID) AS NAME, GET_BOOKNAME(BOOKID) AS BOOKNAME, O.* FROM ORDERS O 
WHERE GET_CUSTNAME(CUSTID) LIKE '김%';
--===========================================
--데이터 처리 방법 
--함수(FUNCTION) 사용 작성 
SELECT O.*,GET_BOOKNAME(BOOKID) AS BOOKNAME, GET_CUSTNAME(CUSTID) AS NAME FROM ORDERS O;
--서브쿼리 사용 작성  
SELECT O.*
    ,(SELECT BOOKNAME FROM BOOK WHERE BOOKID = O.BOOKID) AS BOOK_NAME
    ,(SELECT NAME FROM CUSTOMER WHERE CUSTID = O.CUSTID) AS CUST_NAME
FROM ORDERS O;
--3개 테이블 조인 사용 작성  
SELECT O.*
    , B.BOOKNAME
    , C.NAME
FROM ORDERS O, BOOK B, CUSTOMER C
WHERE O.BOOKID = B.BOOKID 
AND O.CUSTID = C.CUSTID
;
