--(MDGUEST) BOOK 테이블 조회
SELECT * FROM MADANG.BOOK;

SELECT * FROM MADANG.CUSTOMER;
UPDATE MADANG.CUSTOMER
    SET PHONE = '010-1111-1111' 
WHERE CUSTID = 5;

GRANT SELECT ON MADANG.CUSTOMER TO MYSTUDY;
